sudo: required
dist: trusty

language: java
jdk: oraclejdk8

before_script:
  - cd $HOME && mkdir tests  && cd tests && git clone https://github.com/ethereum/tests.git . && cd $TRAVIS_BUILD_DIR

# publish snapshots to https://oss.jfrog.org/libs-snapshot/org/ethereum/ethereumj-core
# publish releases to http://jcenter.bintray.com/org/ethereum/ethereumj-core
# publish coverage to https://coveralls.io/r/ethereum/ethereumj
script:
  - ./gradlew clean build publish jacocoTestReport coveralls $TESTS_OPTS --stacktrace --info


cache:
  directories:
    - $HOME/.gradle

notifications:
  irc:
    channels: chat.freenode.net#ethereumj
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: "Fhaoka5w5XzIZS7ObKfVrnHaVLz7x2Owo1ygb+hXWAHiXpc3Oi1Q6yDOfye/z+Y0Gw8an8v23PIxhLoVZ6JpdurwCXo66dK2TkiNzmEWd6RtYPSZDm6f+0NjPBSOnP5rHmej7RvHeyTY/PQrGPtrHZZQTYD3AuRP1S+tGvtqikA="
  webhooks:
    on_success: change
    on_failure: always
    urls:
      - secure: "Ir1slcCUTWEbV5e39JPGIKYYnjvszD9L7/27TUkqDxiOl6iA4BY6vvg/e0dyZHR6VwbqEedGeEbxpkifZAJ5W/PE88jFa1PHuDHuEy309hWt+u1n2wY1jANnW/VPHO7v/p7oSeMa91cmRUJaIp5TB6hBW0i4CZxTGmwowFnu9y0="


# Encrypted values are ORG_GRADLE_PROJECT_bintrayUser and ORG_GRADLE_PROJECT_bintrayKey props for use by Travis when
# authenticating against oss.jfrog.org and/or Bintray repositories. See http://docs.travis-ci.com/user/encryption-keys
# http://www.gradle.org/docs/current/userguide/tutorial_this_and_that.html#sec:gradle_properties_and_system_properties
env:
  global:
    - JAVA_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
    - TESTS_OPTS="-DGitHubTests.testPath=$HOME/tests"
    - secure: "gPsPLKY5mOiB28FLVC35iveJWYsRpi4+AC9qdPgrwv9ZkcLyTac2Sb34jzKNMq2ZxswZ5u+PRHgguoF4HmxLWAR1st22usnLwqF+mxSs/+/VtVzssYDn5iXeuSIH0BHfRdCoIu41GSrI/e9OJ8V1tt4q9cz1ROHkdBn3J9w1J6M="
    - secure: "PPY1S2n83Vbca/t2nKiN8xUt8BUOGrwFG7rvsxJBc2i2tCJR7iYDt0EFBE4I2Up8kV7mcVaDHTrts5sylykFRN57jiSA5NqtqPodPIekJ/A9vNwmP6Ok6pMN+mOeoJOXfFZ7SfJQqSDNMHtdPm8q+2gwVzzfu0qJ1Hp5iWOZFD0="
